### ISSUE TITLE
Authentication failed because the remote party has closed the transport stream.

### ISSUE THREAD

**Issue by Dre-Tas** [ngocnicholas/airtable.net#36]
Hi,

I am using AirTable to store some regex patterns that my Console app is going to retrieve. When I run my program, it works well and I'm able to retrieve and use the data, but when I test my methods with xUnit I get an _Authentication failed because the remote party has closed the transport stream._ error and my tests fail because they're not able to retrieve the data.

I'm not sure if it's similar to the issue [here](https://github.com/ngocnicholas/airtable.net/issues/13) but I'm not specifying TLS anywhere. Also, I am using .NET Framework 4.7.2

Do you have an idea why this is happening?

**Comment by ngocnicholas** [comment]
Airtable's requirement of TLS1.2 has been supported since Airtable.net 1.0.2 in 2019.
Yes, your issue is similar to the closed ones below:
https://github.com/ngocnicholas/airtable.net/issues/13  
https://github.com/ngocnicholas/airtable.net/issues/31
However I also found the links below which should help you for the time being. According to the info from the link below I also hope that this issue will be fixed in TLS 1.3.  
https://github.com/xunit/xunit/issues/1659
https://stackoverflow.com/questions/44751179/tls-1-2-not-negotiated-in-net-4-7-without-explicit-servicepointmanager-security

**Comment by Dre-Tas** [comment]
I followed the instructions in the StackOverflow thread and added `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12` to my code. Not the best option, but it works for now.

Do you have suggestions on how to avoid hardcoding the TLS version in the code (so that it will support future versions too)?

Thanks for the help!

**Comment by ngocnicholas** [comment]
You can try to set the TLS version in your app.config file. The links in the comments when I closed this issues have some information about this.
